on: push
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4
        with:
          path: joey-photo

      - name: ğŸ“‚ Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: ğŸ“‚ Install npm dependencies
        run: cd joey-photo && npm install

      - name: ğŸ› ï¸ Build project
        run: cd joey-photo && npm run build

      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.cluster121.hosting.ovh.net
          username: grassyi
          password: ${{ secrets.ftp_password }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/src/**
            **/public/**
          server-dir: /www/
          local-dir: joey-photo/dist/
          protocol: ftp
          port: 21
